[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "umap-project"
dynamic = ["version"]
description = "Create maps with OpenStreetMap layers in a minute and embed them in your site."
readme = "README.md"
authors = [
  { name = "Yohan Boniface", email = "yb@enix.org" },
]
maintainers = [
  { name = "David Larlet", email = "david@larlet.fr" },
]
homepage = "https://github.com/umap-project/umap"
keywords = ["django", "leaflet", "geodjango", "openstreetmap", "map"]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "Django==5.0.6",
  "django-agnocomplete==2.2.0",
  "django-environ==0.11.2",
  "django-probes==1.7.0",
  "Pillow==10.3.0",
  "psycopg==3.1.19",
  "pydantic==2.7.4",
  "requests==2.32.3",
  "rcssmin==1.1.2",
  "rjsmin==1.2.2",
  "social-auth-core==4.5.4",
  "social-auth-app-django==5.4.1",
  "websockets==12.0",
]

[project.optional-dependencies]
dev = [
  "hatch==1.12.0",
  "ruff==0.4.9",
  "djlint==1.34.1",
  "mkdocs==1.6.0",
  "mkdocs-material==9.5.27",
  "mkdocs-static-i18n==1.2.3",
  "vermin==1.6.0",
  "pymdown-extensions==10.8.1",
  "isort==5.13.2",
]
test = [
  "factory-boy==3.2.1",
  "playwright>=1.39",
  "pytest==8.2.2",
  "pytest-django==4.8.0",
  "pytest-playwright==0.5.0",
  "pytest-xdist>=3.5.0,<4",
]
docker = [
  "uwsgi==2.0.26",
]

[project.scripts]
umap = "umap.bin:main"

[tool.hatch.build]
artifacts = [
  # Required because part of .gitignore (and thus excluded by hatch).
  "/umap/static/umap/vendors",
]

[tool.hatch.build.targets.sdist]
include = [
  "/umap",
]

[tool.hatch.build.targets.wheel]
packages = ["umap"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "umap/__init__.py"

[tool.flake8]
# Black crazyness.
max-line-length = 88

[tool.djlint]
profile="django"
indent=2
format_css=true
